name: Release

on:
  release:
    types: [created]  # Triggered when a new release is created (via GitHub UI or API)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Set up JDK
        uses: actions/setup-java@v4.7.1
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: gradle

      - name: Decode keystore from Base64
        run: |
          echo "${{ secrets.KEYSTORE_FILE_BASE64 }}" | base64 --decode > keystore.jks

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Build signed release APK
        run: ./gradlew assembleRelease
        env:
          KEYSTORE_FILE: ${{ github.workspace }}/keystore.jks
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: Upload release APK
        uses: actions/upload-artifact@v4.6.2
        with:
          name: signed-apk
          path: app/build/outputs/apk/release/*.apk